tickers={
        'Todos':' ',
        'AAPL':'Apple Inc.',
        'META':'Meta Platforms, Inc.',
        'AMZN':'Amazon.com, Inc.',
        'BAC':'Bank of America Corporation',
        'CVX':'Chevron Corporation',
        'GLD':'SPDR Gold Shares',
        'MRNA':'Moderna, Inc.',
        'NFLX':'Netflix, Inc.',
        'QQQ':'Invesco QQQ Trust',
        'SLV':'iShares Silver Trust ',
        'SPY':'SPDR S&P 500 ETF',
        'TNA':'Direxion Daily Small Cap Bull 3X Shares',
        'TSLA':'Tesla, Inc.',
        'USO':'United States Oil Fund, LP',
        'XOM':'Exxon Mobil Corporation',
        'MSFT':'Microsoft',
        'NVDA':'NVIDIA Corp',
        'WMT':'Walmart Inc',
        'BA':'The Boeing Company',
        'DIS':'Walt Disney Co',
        'CAT':'Caterpillar Inc',
        'IBM':'International Business Machines Corp',
        'WFC':'Wells Fargo & Co',
        'PLTR':'Palantir Technologies Inc',
        'AMD':'Advanced Micro Devices Inc',
        'AVGO':'Broadcom Inc',
        'HOOD':'Robinhood Markets, Inc',
        'CRWV':'CoreWeave, Inc',
        'MSTR':'Microstrategy Inc',
        'UNH':'UnitedHealth Group Inc',
        'GOOG':'Alphabet Inc',
        'APP':'AppLovin Corporation',
        'UBER':'Uber Technologies Inc'
        #'TZA':'Direxion:Sm Cap Bear 3X'
        }